# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: fix-encoding-pragma
            args: ["--remove"]
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: ["--fix=lf"]
            description: Forces to replace line ending by the UNIX 'lf' character.
          - id: check-added-large-files
            args: ["--maxkb=500"]
          - id: no-commit-to-branch
            args: [--branch, staging]
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: pretty-format-json
            files: ^({PROJECT_NAME}/app/|tests/)
            args:
                [--autofix, --no-ensure-ascii, --no-sort-keys, --indent, "    "]
          - id: check-ast
          - id: debug-statements
          - id: check-docstring-first
    - repo: local
      hooks:
          - id: autoflake
            name: Remove unused variables and imports
            entry: poetry run autoflake
            files: ^({PROJECT_NAME}/app/|tests/)
            args:
                [
                    "--in-place",
                    "--remove-all-unused-imports",
                    "--remove-unused-variables",
                    "--expand-star-imports",
                    "--ignore-init-module-imports",
                ]
            language: system
            types: [python]
            verbose: true
          - id: isort
            name: Sorting import statements
            entry: poetry run isort
            files: ^({PROJECT_NAME}/app/|tests/)
            language: system
            types: [python]
            args: ["--filter-files"]
          - id: black
            name: Fix formatting for the entire codebase
            entry: poetry run black
            files: ^({PROJECT_NAME}/app/|tests/)
            language: system
            types: [python]
            verbose: true
          - id: flake8
            name: Lint code base
            entry: poetry run flake8
            files: ^({PROJECT_NAME}/app/|tests/)
            language: system
            types: [python]
            verbose: true
          - id: mypy
            name: local mypy
            description: static type checker
            entry: poetry run mypy
            files: ^({PROJECT_NAME}/app/|tests/)
            language: system
            types: [python]
          - id: pytest
            name: run tests
            entry: poetry run pytest
            types: [python]
            language: system
            pass_filenames: false
            always_run: true
          - id: coverage
            name: local pytest coverage
            description: runs pytest along with coverage
            entry: poetry run pytest --cov tests/
            files: ^({PROJECT_NAME}/tests/)
            language: system
            types: [python]
          - id: safety
            name: local safety
            description: check for vulnerabilities in packages.
            entry: poetry run safety check
            language: system
            types: [python]
            pass_filenames: false
